import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST() {
  try {
    // Clear existing data
    await prisma.peopleManagement.deleteMany({});

    // Seed data based on the static data structure
    const peopleData = [
      // คณะผู้บริหาร (executives)
      {
        full_name: "นายรุ่งโรจน์ กิติพิศาลกุล",
        position: "นายกเทศมนตรีตำบลบ้านโพธิ์",
        phone: "063-795-2282",
        department: "executive",
        role_type: "head",
        level: 1,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายจำเนียร จันทร์สร้อย",
        position: "รองนายกเทศมนตรีตำบลบ้านโพธิ์",
        phone: "086-733-5064",
        department: "executive",
        role_type: "deputy",
        level: 2,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายไชยวัฒน์ ศรีวิไลสกุลวงศ์",
        position: "รองนายกเทศมนตรีตำบลบ้านโพธิ์",
        phone: "081-910-0491",
        department: "executive",
        role_type: "deputy",
        level: 2,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "ว่าง",
        position: "เลขานุการนายกเทศมนตรี",
        department: "executive",
        role_type: "staff",
        level: 3,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "นายประดิษฐ โรจนพร",
        position: "ที่ปรึกษานายกเทศมนตรี",
        phone: "081-686-8366",
        department: "executive",
        role_type: "staff",
        level: 3,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },

      // สภาเทศบาล - ผู้นำ (council leadership)
      {
        full_name: "นายทนง อุดมเดช",
        position: "ประธานสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        role_type: "head",
        level: 1,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายประยูร เมธีกุล",
        position: "รองประธานสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        role_type: "deputy",
        level: 2,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },

      // สภาเทศบาล - เขต 1
      {
        full_name: "นายนิมิตร พานิชย์วัฒนานนท์",
        position: "สมาชิกสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        district: "เขต 1",
        role_type: "staff",
        level: 3,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายอนันต์ วัฒนพานิช",
        position: "สมาชิกสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        district: "เขต 1",
        role_type: "staff",
        level: 3,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายวรวิทย์ รุ่งเรืองกิจพัฒนา",
        position: "สมาชิกสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        district: "เขต 1",
        role_type: "staff",
        level: 3,
        sort_order: 3,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายอัฏธพล กิจไพบูลย์วัฒนา",
        position: "สมาชิกสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        district: "เขต 1",
        role_type: "staff",
        level: 3,
        sort_order: 4,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางมาลี สนรักษา",
        position: "สมาชิกสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        district: "เขต 1",
        role_type: "staff",
        level: 3,
        sort_order: 5,
        img: "/image/placeholder-person.svg",
      },

      // สภาเทศบาล - เขต 2
      {
        full_name: "นายนพพร วัฒนกุล",
        position: "สมาชิกสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        district: "เขต 2",
        role_type: "staff",
        level: 3,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายชัชชาย แจ้งประจักษ์",
        position: "สมาชิกสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        district: "เขต 2",
        role_type: "staff",
        level: 3,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายชาญวิทย์ พ่วงศรีนวล",
        position: "สมาชิกสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        district: "เขต 2",
        role_type: "staff",
        level: 3,
        sort_order: 3,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายบรรพต พัดทอง",
        position: "สมาชิกสภาเทศบาลตำบลบ้านโพธิ์",
        department: "council",
        district: "เขต 2",
        role_type: "staff",
        level: 3,
        sort_order: 4,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "รอการเลือกตั้ง",
        position: "สมาชิกสภาเทศบาล",
        department: "council",
        district: "เขต 2",
        role_type: "staff",
        level: 3,
        sort_order: 5,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },

      // สำนักปลัดเทศบาล (clerk)
      {
        full_name: "นางสาววิไลรัตน์ ขาวมรดก",
        position: "หัวหน้าสำนักปลัดเทศบาล",
        phone: "092-459-0549",
        department: "clerk",
        role_type: "head",
        level: 1,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวบุษบา เชิดชู",
        position: "หัวหน้าฝ่ายอำนวยการ",
        department: "clerk",
        sub_department: "ฝ่ายอำนวยการ",
        role_type: "deputy",
        level: 2,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางอัจฉรา หร่ายเจริญ",
        position: "หัวหน้าฝ่ายปกครอง",
        department: "clerk",
        sub_department: "ฝ่ายปกครอง",
        role_type: "deputy",
        level: 2,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวรุจิยา ลิ้มเจริญผล",
        position: "เจ้าพนักงานธุรการปฏิบัติงาน",
        department: "clerk",
        role_type: "staff",
        level: 3,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวโชติมาส ไทยเจริญ",
        position: "นักวิชาการสุขาภิบาลปฏิบัติการ",
        department: "clerk",
        role_type: "staff",
        level: 3,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "ว่าง",
        position: "นักพัฒนาชุมชนชำนาญการ",
        department: "clerk",
        role_type: "staff",
        level: 3,
        sort_order: 3,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "นายโมไนย นาควงศ์วาลย์",
        position: "นักจัดการงานทะเบียนและบัตรปฏิบัติการ",
        department: "clerk",
        role_type: "staff",
        level: 3,
        sort_order: 4,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวนพวรรณ โภคทรัพย์",
        position: "เจ้าพนักงานธุรการ",
        department: "clerk",
        role_type: "staff",
        level: 3,
        sort_order: 5,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางขนิษฐา ศรีแก้ว",
        position: "ผู้ช่วยนักวิเคราะห์นโยบายและแผน",
        department: "clerk",
        role_type: "staff",
        level: 4,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวปิยะพัชร์ ช่อผกา",
        position: "ผู้ช่วยเจ้าพนักงานพัฒนาชุมชน",
        department: "clerk",
        role_type: "staff",
        level: 4,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายปฐม เซ็ทเจริญ",
        position: "พนักงานขับรถยนต์",
        department: "clerk",
        role_type: "worker",
        level: 5,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวณัฏฐนันท์ น่วมรัสมี",
        position: "ผู้ช่วยเจ้าพนักงานธุรการ",
        department: "clerk",
        role_type: "staff",
        level: 4,
        sort_order: 3,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวธัญญสรัณ อำสันเทียะ",
        position: "ผู้ช่วยเจ้าพนักงานธุรการ",
        department: "clerk",
        role_type: "staff",
        level: 4,
        sort_order: 4,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายประยูร วิญญูวิญ",
        position: "พนักงานขับเครื่องจักรกลขนาดเบา",
        department: "clerk",
        role_type: "worker",
        level: 5,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายประเสริฐ เคลือบสำราญ",
        position: "พนักงานขับเครื่องจักรกลขนาดเบา",
        department: "clerk",
        role_type: "worker",
        level: 5,
        sort_order: 3,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายวิโรจน์ สินกังวาน",
        position: "ผู้ช่วยเจ้าหน้าที่ป้องกัน",
        department: "clerk",
        role_type: "staff",
        level: 4,
        sort_order: 5,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายประชา ประเสริฐศิลป์",
        position: "คนงาน (รถดับเพลิง)",
        department: "clerk",
        role_type: "worker",
        level: 6,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายเกียรติ หลายทอง",
        position: "คนงานประจำรถขยะ",
        department: "clerk",
        role_type: "worker",
        level: 6,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายพิษณุ สุขประเสริฐ",
        position: "พนักงานขับเคลื่อนจักรกลขนาดเบา (รถขยะ)",
        department: "clerk",
        role_type: "worker",
        level: 5,
        sort_order: 4,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายภานุวัฒน์ คงยิ้ม",
        position: "คนงาน",
        department: "clerk",
        role_type: "worker",
        level: 6,
        sort_order: 3,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายพรพิรุณ นุชน้อย",
        position: "คนงาน",
        department: "clerk",
        role_type: "worker",
        level: 6,
        sort_order: 4,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายอนันต์ กลัดสุขใส",
        position: "คนงานประจำรถขยะ",
        department: "clerk",
        role_type: "worker",
        level: 6,
        sort_order: 5,
        img: "/image/placeholder-person.svg",
      },

      // กองคลัง (finance)
      {
        full_name: "นางสาวจุฬาลัย มงคลชัยฤกษ์",
        position: "ผู้อำนวยการกองคลัง",
        phone: "063-874-4595",
        department: "finance",
        role_type: "head",
        level: 1,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "ว่าง",
        position: "หัวหน้าฝ่ายบริหารงานคลัง",
        department: "finance",
        sub_department: "ฝ่ายบริหารงานคลัง",
        role_type: "deputy",
        level: 2,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "ว่าง",
        position: "หัวหน้าฝ่ายพัฒนารายได้",
        department: "finance",
        sub_department: "ฝ่ายพัฒนารายได้",
        role_type: "deputy",
        level: 2,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "ว่าง",
        position: "นักวิชาการพัสดุชำนาญการ",
        department: "finance",
        role_type: "staff",
        level: 3,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "นางสาวลักขณาณัฐ์ อรัณยะกานนท์",
        position: "เจ้าพนักงานจัดเก็บรายได้ชำนาญงาน",
        department: "finance",
        role_type: "staff",
        level: 3,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "ว่าง",
        position: "นักวิชาการเงินและบัญชี",
        department: "finance",
        role_type: "staff",
        level: 3,
        sort_order: 3,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "นางสาวนันทพร ชัยยะ",
        position: "เจ้าพนักงานธุรการ",
        department: "finance",
        role_type: "staff",
        level: 3,
        sort_order: 4,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาววรณัน บุษบงก์",
        position: "เจ้าพนักงานธุรการ",
        department: "finance",
        role_type: "staff",
        level: 3,
        sort_order: 5,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวเบญจวรรณ วงษ์สำเริงชัย",
        position: "ผู้ช่วยเจ้าพนักงานการเงินและบัญชี",
        department: "finance",
        role_type: "staff",
        level: 4,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },

      // กองช่าง (engineering)
      {
        full_name: "นายพิเชฐ สระอุบล",
        position: "ผู้อำนวยการกองช่าง",
        phone: "089-833-3244",
        department: "engineering",
        role_type: "head",
        level: 1,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "ว่าง",
        position: "หัวหน้าฝ่ายการโยธา",
        department: "engineering",
        sub_department: "ฝ่ายการโยธา",
        role_type: "deputy",
        level: 2,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "ว่าง",
        position: "วิศวกรโยธา",
        department: "engineering",
        role_type: "staff",
        level: 3,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "นางสาวลภัสรดา อินทร์ศรี",
        position: "ผู้ช่วยเจ้าพนักงานจัดเก็บรายได้",
        department: "engineering",
        role_type: "staff",
        level: 4,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวรุ่งนภา พุ่มประเสริฐ",
        position: "คนงาน",
        department: "engineering",
        role_type: "worker",
        level: 6,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "ว่าง",
        position: "พนักงานผลิตน้ำประปา",
        department: "engineering",
        role_type: "worker",
        level: 5,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "นายกรศุทธิ์ มั่นคง",
        position: "คนงาน",
        department: "engineering",
        role_type: "worker",
        level: 6,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "ว่าง",
        position: "คนงาน",
        department: "engineering",
        role_type: "worker",
        level: 6,
        sort_order: 3,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "นายบุญธรรม พรบุญ",
        position: "คนงาน",
        department: "engineering",
        role_type: "worker",
        level: 6,
        sort_order: 4,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายกิติศักดิ์ มูลสิติ",
        position: "คนงาน",
        department: "engineering",
        role_type: "worker",
        level: 6,
        sort_order: 5,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายไพโรจน์ กำแพงทอง",
        position: "คนงาน",
        department: "engineering",
        role_type: "worker",
        level: 6,
        sort_order: 6,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายอนณ เตียวหยิน",
        position: "พนักงานขับเครื่องจักรกลขนาดเบา",
        department: "engineering",
        role_type: "worker",
        level: 5,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นายพิมล แช่มเจริญ",
        position: "พนักงานจ้างเหมา",
        department: "engineering",
        role_type: "worker",
        level: 6,
        sort_order: 7,
        img: "/image/placeholder-person.svg",
      },

      // กองการศึกษาฯ (education)
      {
        full_name: "ว่าง",
        position: "ผู้อำนวยการกองการศึกษา",
        department: "education",
        role_type: "head",
        level: 1,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "ว่าง",
        position: "หัวหน้าฝ่ายบริหารการศึกษา",
        department: "education",
        sub_department: "ฝ่ายบริหารการศึกษา",
        role_type: "deputy",
        level: 2,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
      {
        full_name: "นางสาวปิยภาณี ตาอุดม",
        position: "นักวิชาการศึกษาปฏิบัติการ",
        department: "education",
        role_type: "staff",
        level: 3,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาววิลาวัลย์ กิตติรัตนโรจน์",
        position: "ผู้ช่วยเจ้าพนักงานธุรการ",
        department: "education",
        role_type: "staff",
        level: 4,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางจรินทร์พร วิไลพันธุ์",
        position: "ครู คศ.๑",
        department: "education",
        role_type: "staff",
        level: 3,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวสาลักษณ์ เพียรอริยพร",
        position: "พนักงานจ้างเหมา",
        department: "education",
        role_type: "worker",
        level: 6,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
      },
      {
        full_name: "นางสาวกนิษฐา อุทัยสา",
        position: "พนักงานจ้างเหมา",
        department: "education",
        role_type: "worker",
        level: 6,
        sort_order: 2,
        img: "/image/placeholder-person.svg",
      },

      // หน่วยตรวจสอบภายใน (audit)
      {
        full_name: "ว่าง",
        position: "นักวิชาการตรวจสอบภายใน",
        department: "audit",
        role_type: "head",
        level: 1,
        sort_order: 1,
        img: "/image/placeholder-person.svg",
        is_empty: true,
      },
    ];

    // Insert all people data
    const createdPeople = await prisma.peopleManagement.createMany({
      data: peopleData,
    });

    return NextResponse.json({
      success: true,
      message: `Successfully seeded ${createdPeople.count} people records`,
      count: createdPeople.count,
    });
  } catch (error) {
    console.error("Error seeding people management:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to seed people management data",
        details: error.message,
      },
      { status: 500 }
    );
  }
}